### PR TITLE
Buttons: Add new action for Appcues show

### PR DESCRIPTION
**Pull request by helenphan0**
screen shot 2017-09-13 at 6 03 23 pm

### CODE REVIEW

**Comment by brettcrowell** [comment]
Already?!

**Comment by GuruM** [comment]
Looks legit to me 🍩

**Comment by helenphan0** [comment]
screen shot 2017-09-14 at 9 59 06 am

I think this might be necessary in case the triggered flow will show up underneath the current slideout or modal, this gives our customers the ability to automatically close the current step.

**Comment by brettcrowell** [comment]
Have you noticed multiple flows showing at once, @helenphan0?  That shouldn't be possible the way the SDK is written, but this is the second time I've heard it in as many days 🤔

**Comment by helenphan0** [comment]
Brett, you're right. I saw multiple flows on top of one another in Preview mode, but testing it in its Published state was fine. I'll change it back

**Comment by GuruM** [comment]
Multiple shows flowing is possible in preview if the client website has Appcues installed. We try to `Appcues.reset` the client website's Appcues SDK to avoid it showing anything, but it could still be triggered later on.

**Comment by helenphan0** [comment]
One last thing to throw in this: without data-step=end, this button won't register as a flow event on the SDK. That means if it's on a modal/slideout, a user triggers the Appcues.show action, and continues on, this step will never be "complete". This is the current behavior when customers create their own buttons, but this could also be an opportunity to make it right.

**Pull request merged**
